
project_id = "gftbjdazuhjcvqvssyiu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[ingest]
enabled = true
port = 54324

[auth]
enabled = true
port = 54325
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[functions.create-checkout]
verify_jwt = true

[functions.handle-stripe-webhook]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true
