// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gftbjdazuhjcvqvssyiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmdGJqZGF6dWhqY3ZxdnNzeWl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMjQ1OTgsImV4cCI6MjA2MzcwMDU5OH0.RJqAGoNmboA5zCdQWDQ1yi3rOWCW3Sk5aFDpg8o6yL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);